PPWStory2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Story6/', include('Story6.urls')),
    path('Story7/', include('Story7.urls')),
    path('Story8/', include('Story8.urls')),
    path('Story9/', include('Story9.urls')),
]

Story6/urls.py
from . import views
from django.urls import path

app_name = 'story6'

urlpatterns = [
	path('', views.activity_list, name='activity_list'),
	path('add-activity/', views.add_activity, name='add_activity'),
	path('add-participants/<int:activity_id>', views.add_participant, name='add_participant'),
]

Story7/urls.py
from . import views
from django.urls import path

app_name = 'Story7'

urlpatterns = [
	path('', views.page, name='page'),
]

Story8/urls.py
from . import views
from django.urls import path

app_name = 'Story8'

urlpatterns = [
	path('', views.index, name='index'),
	path('data/', views.data, name='data'),
]

Story9/urls.py
from django.urls import path
from . import views

app_name = "Story9"

urlpatterns = [
	path('', views.home, name='home'),
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
]

Story6/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):

	class Meta:
		verbose_name_plural = 'Activities'

	activity_name = models.CharField(max_length=255)

	def __str__(self):
		return self.activity_name

class Participant(models.Model):

	class Meta:
		verbose_name_plural = 'Participants'

	participant_name = models.CharField(max_length=255)
	activity = models.ForeignKey(Activity, on_delete=models.CASCADE)

	def __str__(self):
		return (self.participant_name + " - " + self.activity.activity_name)

Story7/models.py
from django.db import models

# Create your models here.

Story8/models.py
from django.db import models

# Create your models here.

Story9/models.py
from django.db import models

# Create your models here.

Story6/forms.py
from django import forms
from .models import Activity, Participant

class ActivityForm(forms.ModelForm):
	class Meta:
		model = Activity
		fields = [
			'activity_name'
		]

		labels = {
			'activity_name': 'Nama kegiatan'
		}

		widgets = {
			'activity_name': forms.TextInput(
				attrs = {
					'class': 'form-control',
					'placeholder': 'Masukkan nama kegiatan...'
				}
			)
		}

class ParticipantForm(forms.ModelForm):
	class Meta:
		model = Participant
		fields = [
			'participant_name'
		]

		labels = {
			'participant_name': 'Nama peserta'
		}

		widgets = {
			'participant_name': forms.TextInput(
				attrs = {
					'class': 'form-control',
					'placeholder': 'Masukkan nama peserta...'
				}
			)
		}

Story6/views.py
from django.shortcuts import render, redirect
from .forms import ActivityForm, ParticipantForm
from .models import Activity, Participant

# Create your views here.
def activity_list(request):
	activities = Activity.objects.all()
	activity_list = []
	for activity in activities:
		participants_in_activity = activity.participant_set.all()
		activity_list.append({
			'activity': activity,
			'participants': participants_in_activity 
		})
	response = {
		'title': 'Daftar Kegiatan',
		'activity_list': activity_list
	}

	return render(request, 'activity_list.html', response)

def add_activity(request):
	if (request.method == "POST"):
		activity_form = ActivityForm(request.POST)
		if activity_form.is_valid():
			activity_form.save()
		return redirect('story6:activity_list')
	else:
		activity_form = ActivityForm()
		response = {
			'title': 'Tambah Kegiatan',
			'activity_form': activity_form
		}
		return render(request, 'activity_form.html', response)

def add_participant(request, activity_id):
	if (request.method == "POST"):
		participant_form = ParticipantForm(request.POST)
		if participant_form.is_valid():
			activity = Activity.objects.get(id=activity_id)
			participant = participant_form.save(commit=False)
			participant.activity = activity
			participant.save()
			return redirect('story6:activity_list')
	else:
		participant_form = ParticipantForm()
		response = {
			'title': 'Tambah Peserta',
			'participant_form': participant_form,
			'activity': Activity.objects.get(id=activity_id),
		}
		return render(request, 'participant_form.html', response)

Story7/views.py
from django.shortcuts import render

# Create your views here.
def page(request):
	return render(request,'page.html')

Story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests

# Create your views here.
def index(request):
	return render(request,'index.html')

def data(request):
	q = request.GET['q']
	url = 'https://www.googleapis.com/books/v1/volumes?q=' + q
    
	response = requests.get(url)
	response_json = response.json()
	return JsonResponse(response_json)

Story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def home(request):
    return render(request, 'home.html')

def sign_up(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            #add session
            request.session['name'] = user.username
            return redirect('Story9:home')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form, 'errors': form.errors})
	  
def log_in(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            #add session
            request.session['name'] = user.username
            return redirect('Story9:home')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form, 'errors': form.errors})

def log_out(request):
    if request.method == 'POST':
        logout(request)
        #delete session
        request.session.flush()
        return redirect('Story9:login')

Story6/templates/activity_form.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/stylestory6.css' %}">
{% endblock %}

{% block content %}
<div class="center">
	<h2 style="text-align: center;">{{ title }}</h2>
	<form action="{% url 'story6:add_activity' %}" method="POST">
		{% csrf_token %}
		{% for field in activity_form.visible_fields %}
			<div class="form-group">
                <div class="col-sm-6 offset-sm-3">
                    <h5>{{field.label_tag}} {{field}}</h5>
                </div>
            </div>
		{% endfor %}
		<div style="text-align: center"><button type="submit">Submit</button></div>
	</form>
</div>
{% endblock %}

Story6/templates/activity_list.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/stylestory6.css' %}">
{% endblock %}

{% block content %}
{% if activity_list %}
<div class="flex-wrap">
	{% for activity_item in activity_list %}
		<div class="card">
			<h2>{{ activity_item.activity.activity_name }}</h2>
			<br/>
			<br/>
			
			<h3>Peserta:</h3>
			<div class="participants">
				{% if activity_item.participants.count %}
				{% for participant in activity_item.participants %}
					<li>{{ participant.participant_name }}</li>
				{% endfor %}
				{% else %}
				-
				{% endif %}
			</div>
			<div class="center">
				<button><a href="{% url 'story6:add_participant' activity_id=activity_item.activity.id %}">Tambah peserta!</a></button>
			</div>
		</div>
	{% endfor %}
</div>
<div style="display: flex; justify-content: center;">
	<button><a href="{% url 'story6:add_activity' %}">Tambah Kegiatan!</a></button>
</div>
{% else %}
<div class="centered">
	<div class="column">
		<div class="empty">Tambah kegiatan sekarang!</div>
		<button><a href="{% url 'story6:add_activity' %}">Tambah!</a></button>
	</div>
</div>
{% endif %}
{% endblock %}

Story6/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Story 6">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {% block css %}
    {% endblock %}

    <!-- Title -->
    <title>{{ title }}</title>
</head>
<body class="bg-light">
    {% block content %}
    {% endblock %}
</body>
</html>

Story6/templates/participant_form.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/stylestory6.css' %}">
{% endblock %}

{% block content %}
<div class="center">
	<h2 style="text-align: center;">{{ title }}</h2>
	<form action="{% url 'story6:add_participant' activity_id=activity.id %}" method="POST">
		{% csrf_token %}
		{% for field in participant_form.visible_fields %}
			<div class="form-group">
                <div class="col-sm-6 offset-sm-3">
                    <h5>{{field.label_tag}} {{field}}</h5>
                </div>
            </div>
		{% endfor %}
		<div style="text-align: center"><button type="submit">Submit</button></div>
	</form>
</div>
{% endblock %}

Story7/templates/page.html
{% extends 'base_story_7.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/stylestory7.css' %}">
{% endblock %}

{% block content %}

<div class="page">

	<h1>Hello!<br/>Welcome to my profile :)</h1>

	<div class="accordion" id="script">

		<div id="activity" class="set">
			<li>
				<a>Aktivitas</a>
				<div>
					<button class="up"><b>Up</b></button>
					<button class="down"><b>Down</b></button>
				</div>
				<p>
					<b>- Mahasiswi SI UI 2019</b><br/>
					<b>- Member Consulting SIG SISTEM Fasilkom UI 2020</b><br/>
					<b>- Staff Akademis PMB Fasilkom UI 2020</b>
				</p>
			</li>
		</div>

		<div id="experience" class="set">
			<li>
				<a>Pengalaman Organisasi/Kepanitiaan</a>
				<div>
					<button class="up"><b>Up</b></button>
					<button class="down"><b>Down</b></button>
				</div>
				<p>
					<b>- Member Consulting SIG SISTEM Fasilkom UI 2020</b><br/>
					<b>- Staff Akademis PMB Fasilkom UI 2020</b><br/>
					<b>- Staff Ticketing UIGTC 2020</b><br/>
					<b>- Panitia Natal PO Fasilkom UI 2019</b><br/>
					<b>- Panitia Paskah PO Fasilkom UI 2020</b>
				</p>
			</li>
		</div>

		<div id="achievement" class="set">
			<li>
				<a>Prestasi</a>
				<div>
					<button class="up"><b>Up</b></button>
					<button class="down"><b>Down</b></button>
				</div>
				<p>
					<b>- Medali Perunggu Singapore and Asian Schools Math Olympiad 2016</b><br/>
					<b>- Juara 3 Mathematics Battle Challenge GS Universitas Padjadjaran 2017</b><br/>
					<b>- Juara 1 LCT Matematika Universitas Swadaya Gunung Jati 2018</b><br/>
					<b>- Lulus dengan Predikat Distinction Ujian Piano ABRSM Grade 5 2013</b><br/>
					<b>- Juara 1 Ens Piano Collection 2013 Kategori A</b><br/>
				</p>
			</li>
		</div>

		<div id="education" class="set">
			<li>
				<a>Riwayat Pendidikan</a>
				<div>
					<button class="up"><b>Up</b></button>
					<button class="down"><b>Down</b></button>
				</div>
				<p>
					<b>Universitas Indonesia (2019-sekarang)<br/></b>
					<b>SMA Santa Maria 1 Cirebon (2016-2019)<br/></b>
					<b>SMP Santa Maria Cirebon (2013-2016)<br/></b>
					<b>SDK BPK Penabur Cirebon (2007-2013)<br/></b>
					<b>TK Permata Bunda Cirebon (2005-2007)</b>
				</p>
			</li>
		</div>
	</div>
</div>

<script src='https://code.jquery.com/jquery-3.1.1.min.js'></script>
<script src="{% static 'js/script.js' %}"></script>

{% endblock %}

Story8/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="UTF-8">
    <meta name="description" content="Story 8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="HTML,CSS">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src='https://code.jquery.com/jquery-3.1.1.min.js'></script>
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js'></script>
    <script src="{% static 'js/books.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/stylestory8.css' %}">

    <title>Story 8</title>

</head>

<body>
    <div class="story8-page">
        <br/>
        <h1>I'm searching for this book: </h1>
        <div class="form-group">
            <div class="col-sm-6 offset-sm-3">
                <input id="search" class="form-control" type="text" placeholder="Search books">
            </div>
        </div>
    </div>

    <br/><br/>
    <ol id="result">

    </ol>

</body>

</html> 

Story9/templates/home.html
{% extends 'base_story_9.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/stylestory9.css' %}">
{% endblock %}

{% block content %}

{% if request.session.name %}
<div class="background">
    <div class="homepage">
        <h1><b>Welcome, {{ request.session.name }} :) </b></h1>
        <h3><b>Have a nice day and stay safe!</b></h3>
        <form action="{% url 'Story9:logout' %}" method="POST">
            {% csrf_token %}
            <div style="margin-top: 1rem; display: flex; justify-content: center;">
                <button name="logout" type="submit" value="Log Out"><b>Log Out</b></button> 
        </form> 
    </div>

    {% else %}
    <div class="not-authenticated">
        <b>You're not authenticated. Please Log In. <br/>
        If you don't have an account yet, click Sign Up.</b><br/>
        <div style="margin-top: 1rem;">
            <button><a href="{% url 'Story9:login' %}"><b>Log In</b></a></button>
            <button><a href="{% url 'Story9:signup' %}"><b>Sign Up</b></a></button>
        </div>
    </div>
{% endif %}

<script>
    $("input").addClass("form-control");
</script>

{% endblock %}

Story9/templates/login.html
{% extends 'base_story_9.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/login_story9.css' %}">
{% endblock %}

{% block content %}

<div class="centered">
    <div style="margin-top: 5rem;">
        <h2 style="display: flex; justify-content: center; color: #20639b;"><b>L &nbsp; O &nbsp; G &nbsp; I &nbsp; N</b></h2>
        <form class="site-form" action="{% url 'Story9:login' %}" method="POST">
            <div style="display: flex; justify-content: center;">
                <div class="squared">
                    <div style="padding-top: 2rem;">
                        <div class="form-group">
                            {% csrf_token %}
                            {% for field in form %}
                            <div style="display: flex; justify-content: center;">
                                <div class="pair">
                                    {{field.label_tag}}
                                    <div class="col-sm-12">
                                        {{field}}
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div style="display: flex; justify-content: center;">
                            <div class="signup-button">
                                <input type="submit" value="Log In">
                            </div>
                        </div>
                        <div style="display: flex; justify-content: center; font-size: 12px; padding-top: 0.5rem;">
                            Don't have an account yet?&nbsp; 
                            <a href="{% url 'Story9:signup' %}">Sign Up</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <div style="display: flex; justify-content: center; padding-top: 0.5rem;">
            <div class="error">
                {{errors}}
            </div>
        </div>
    </div>
</div>

<script>
    $("input").addClass("form-control");
</script>

{% endblock %}

Story9/templates/signup.html
{% extends 'base_story_9.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/signup_story9.css' %}">
{% endblock %}

{% block content %}

<div class="centered">
    <div style="margin-top: 5rem;">
        <h2 style="display: flex; justify-content: center; color: #20639b;"><b>S &nbsp; I &nbsp; G &nbsp; N &nbsp; &nbsp; U &nbsp; P</b></h2>
        <form class="site-form" action="{% url 'Story9:signup' %}" method="POST">
            <div style="display: flex; justify-content: center;">
                <div class="squared">
                    <div style="padding-top: 2rem;">
                        <div class="form-group">
                            {% csrf_token %}
                            {% for field in form %}
                            <div style="display: flex; justify-content: center;">
                                <div class="pair">
                                    {{field.label_tag}}
                                    <div class="col-sm-12">
                                        {{field}}
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div style="display: flex; justify-content: center;">
                            <div class="signup-button">
                                <input type="submit" value="Sign Up">
                            </div>
                        </div>
                        <div style="display: flex; justify-content: center; font-size: 12px; padding-top: 0.5rem;">
                            Already have an account?&nbsp; 
                            <a href="{% url 'Story9:login' %}">Log In</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <div style="display: flex; justify-content: center; padding-top: 0.5rem;">
            <div class="error">
                {{errors}}
            </div>
        </div>
    </div>
</div>

<script>
    $("input").addClass("form-control");
</script>

{% endblock %}

templates/base_story_7.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="description" content="Story 7">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="HTML,CSS">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Kurale&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kurale&family=Tenali+Ramakrishna&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    {% block css %}
    {% endblock %}

    <title>Story 7</title>

</head>

<body class="page">

    {% block content %}
    {% endblock %}
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

</body>

</html>

templates/base_story_9.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="description" content="Story 8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="HTML,CSS">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src='https://code.jquery.com/jquery-3.1.1.min.js'></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Livvic:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500&display=swap" rel="stylesheet">

    {% block css %}
    {% endblock %}

    <title>Story 9</title>

</head>

<body class="bg-light">

    {% block content %}
    {% endblock %}

</body>

</html>